apiVersion: v1
kind: Pod
metadata:
  name: simple-node
spec:
  containers:
    - image: simple-node:v1 
      name: simple-node
      ports:
        - containerPort: 3000
          name: http
          protocol: TCP
