apiVersion: v1
kind: Pod
metadata:
  name: simple-node
spec:
  containers:
    - image: localhost/simple-node
      name: simple-node
      ports:
        - containerPort: 3000
          name: http
          protocol: TCP
